services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    # image: minio/minio:RELEASE.2024-12-18T13-15-44Z-cpuv1 # LATEST обрізаний
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: CHANGE_ME
      # (Optional)
      MINIO_PROMETHEUS_AUTH_TYPE: public  
      MINIO_PROMETHEUS_JOB_ID: minio-cluster
      MINIO_PROMETHEUS_URL: http://1.1.1.1:9090
    volumes:
      - /mnt/minio-union/share1:/data1
      - /mnt/minio-union/share2:/data2
      - /mnt/minio-union/share3:/data3
      - /mnt/minio-union/share4:/data4
    command: server http://minio/data{1...4} --console-address ":9001"
